# -*- coding: utf-8 -*-
"""task1_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OWeimpT_-ihqdU5f9qm-LYWlHaGeauL6
"""

import requests
import json
import time
import os
from datetime import datetime

# 1. Setup
TOP_STORIES_URL = "https://hacker-news.firebaseio.com/v0/topstories.json"
ITEM_URL = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HEADERS = {"User-Agent": "TrendPulse/1.0"}

# Use broader keywords to guarantee you hit 100+ stories
CATEGORIES = {
    "technology": ["AI", "software", "tech", "code", "computer", "data", "cloud", "api", "gpu", "llm", "web", "system"],
    "worldnews": ["war", "government", "country", "president", "election", "climate", "attack", "global", "news", "world", "state"],
    "sports": ["nfl", "nba", "fifa", "sport", "game", "team", "player", "league", "championship", "race", "cup"],
    "science": ["research", "study", "space", "physics", "biology", "discovery", "nasa", "genome", "nature", "science", "brain"],
    "entertainment": ["movie", "film", "music", "netflix", "game", "book", "show", "award", "streaming", "video", "art", "tv"]
}

buckets = {cat: [] for cat in CATEGORIES}

print("--- Starting TrendPulse Task 1 ---")
print("Fetching IDs...")
try:
    ids = requests.get(TOP_STORIES_URL, headers=HEADERS, timeout=10).json()[:500]
    print(f"Found {len(ids)} top stories. Starting scan...\n")
except Exception as e:
    print(f"Connection Error: {e}")
    ids = []

# 2. Main Loop with Live Output
for i, s_id in enumerate(ids):
    try:
        # Check if we are done
        if all(len(b) >= 25 for b in buckets.values()): break

        item = requests.get(ITEM_URL.format(s_id), headers=HEADERS, timeout=5).json()
        if not item or 'title' not in item: continue

        title_low = item['title'].lower()

        for cat, keywords in CATEGORIES.items():
            if any(k in title_low for k in keywords) and len(buckets[cat]) < 25:
                story = {
                    "post_id": item['id'],
                    "title": item['title'],
                    "category": cat,
                    "score": item.get('score', 0),
                    "num_comments": item.get('descendants', 0),
                    "author": item.get('by'),
                    "collected_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }
                buckets[cat].append(story)
                # LIVE PRINT: This shows you the script is working!
                print(f"[MATCH] {cat.upper()}: {item['title'][:50]}...")
                break

        # Periodic progress update
        if i % 50 == 0 and i > 0:
            print(f"> Checked {i} stories so far...")

    except:
        continue

# 3. Finalizing and Saving
print("\n--- Applying 2-second sleep per category ---")
final_data = []
for cat in CATEGORIES:
    print(f"Finalizing {cat}...")
    final_data.extend(buckets[cat])
    time.sleep(2)

os.makedirs('data', exist_ok=True)
filename = f"data/trends_{datetime.now().strftime('%Y%m%d')}.json"
with open(filename, 'w') as f:
    json.dump(final_data, f, indent=4)

print(f"\nSUCCESS! Total stories: {len(final_data)}")
print(f"Saved to {filename}")